/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.cts.pnrservice.api;

import javax.validation.constraints.NotNull;

import org.springframework.cloud.sleuth.annotation.NewSpan;
//import org.springframework.cloud.sleuth.annotation.NewSpan;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.cts.pnrservice.model.RetrievePnrFault;
import com.cts.pnrservice.model.RetrievePnrResponse;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-01-16T07:29:02.569Z")

@Api(value = "retrievePnr", description = "the retrievePnr API")
public interface RetrievePnrApi {

    @ApiOperation(value = "Operation RetrievePnr", notes = "", response = RetrievePnrResponse.class, tags={ "Pnr", })
    @ApiResponses(value = { 
        @ApiResponse(code = 500, message = "", response = RetrievePnrFault.class),
        @ApiResponse(code = 200, message = "", response = RetrievePnrResponse.class) })
    //@NewSpan
    @RequestMapping(value = "/retrievePnr",
        produces = { "application/json", "application/xml" }, 
        //consumes = {  "application/xml", "application/json", "text/plain" },
        //consumes = { "text/plain"},
        method = RequestMethod.GET)
    ResponseEntity<RetrievePnrResponse> retrievePnr( @NotNull@ApiParam(value = "PnrNo", required = true) @RequestParam(value = "PnrNo", required = true) String pnrNo);

}
